name: Expo Go QR Preview

on:
  pull_request:

jobs:
  preview:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10.6.4

      - name: Install dependencies
        run: pnpm install

      - name: Install QR dependencies
        run: |
          pnpm install qrcode # Proper QR code image generator
          pnpm install -g serve # optional if needed later

      - name: Start Expo dev server (background)
        run: |
          nohup pnpm dlx expo start --tunnel --non-interactive > expo.log 2>&1 &
          sleep 30  # Give Expo time to initialize

      - name: Extract Expo QR URL
        id: extract_qr
        run: |
          echo "EXPO_URL=$(grep -o 'exp:\/\/[^ ]*' expo.log | head -n 1)" >> $GITHUB_ENV
          echo "QR_TEXT=exp://$(echo $EXPO_URL | cut -d'/' -f3-)" >> $GITHUB_ENV

      - name: Generate QR image
        run: |
          mkdir -p qr
          node -e "require('qrcode').toFile('./qr/expo-qr.png', '${{ env.QR_TEXT }}', { margin: 1, width: 400 }, (err) => { if (err) throw err })"

      - name: Upload QR image
        uses: actions/upload-artifact@v4
        with:
          name: expo-qr
          path: qr/expo-qr.png

      - name: Base64 encode QR image
        id: qr_base64
        run: |
          echo "QR_BASE64=$(base64 -w 0 qr/expo-qr.png)" >> $GITHUB_OUTPUT

      - name: Create QR comment
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            📱 Expo Go Preview is ready!

            Scan the QR code below with the [Expo Go](https://expo.dev/client) app to view this PR build.

            <img src="data:image/png;base64,${{ steps.qr_base64.outputs.QR_BASE64 }}" width="200" alt="Expo QR Code"/>

            Or open this URL in Expo Go: `${{ env.EXPO_URL }}`
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}